import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DIRECT_URL || process.env.DATABASE_URL,
    },
  },
})

export async function seedFornecedores() {
  await prisma.fornecedor.createMany({
    data: [
      {
        tipoPessoa: 'Jurídica',
        nome: 'Metalúrgica Delta Ltda',
        cnpj: '12.345.678/0001-10',
        fantasia: 'Delta Metal',
        abertura: new Date('2014-02-15'),
        situacao: 'Ativa',
        tipo: 'MATRIZ',
        porte: 'Médio',
        natureza_juridica: '206-2',
        cep: '01010-000',
        logradouro: 'Av. das Indústrias',
        bairro: 'Centro',
        localidade: 'São Paulo',
        uf: 'SP',
        telefone: '(11) 4002-1001',
        email: 'contato@delta.com.br',
      },
      {
        tipoPessoa: 'Jurídica',
        nome: 'Forplast Indústria de Plásticos',
        cnpj: '98.765.432/0001-20',
        fantasia: 'Forplast',
        abertura: new Date('2018-06-01'),
        situacao: 'Ativa',
        tipo: 'FILIAL',
        porte: 'Pequeno',
        natureza_juridica: '213-5',
        cep: '20020-000',
        logradouro: 'Rua do Progresso',
        bairro: 'Industrial',
        localidade: 'Rio de Janeiro',
        uf: 'RJ',
        telefone: '(21) 3344-5566',
        email: 'vendas@forplast.com',
      },
      {
        tipoPessoa: 'Jurídica',
        nome: 'EletroMix Comercial Ltda',
        cnpj: '21.321.321/0001-30',
        fantasia: 'EletroMix',
        abertura: new Date('2019-09-10'),
        situacao: 'Ativa',
        tipo: 'MATRIZ',
        porte: 'Médio',
        natureza_juridica: '206-2',
        cep: '30130-000',
        logradouro: 'Rua das Máquinas',
        bairro: 'Tecnologia',
        localidade: 'Belo Horizonte',
        uf: 'MG',
        telefone: '(31) 9876-5432',
        email: 'atendimento@eletromix.com',
      },
      {
        tipoPessoa: 'Jurídica',
        nome: 'Tintas Brilho Ltda',
        cnpj: '33.444.555/0001-99',
        fantasia: 'Brilho Tintas',
        abertura: new Date('2012-03-12'),
        situacao: 'Ativa',
        tipo: 'MATRIZ',
        porte: 'Pequeno',
        natureza_juridica: '206-2',
        cep: '80040-000',
        logradouro: 'Av. Colorida',
        bairro: 'Tinturaria',
        localidade: 'Curitiba',
        uf: 'PR',
        telefone: '(41) 3222-8888',
        email: 'sac@brilho.com.br',
      },
      {
        tipoPessoa: 'Jurídica',
        nome: 'TecParts Suprimentos Industriais',
        cnpj: '45.666.777/0001-88',
        fantasia: 'TecParts',
        abertura: new Date('2020-11-05'),
        situacao: 'Ativa',
        tipo: 'FILIAL',
        porte: 'Médio',
        natureza_juridica: '213-5',
        cep: '50050-000',
        logradouro: 'Rua das Peças',
        bairro: 'Centro',
        localidade: 'Recife',
        uf: 'PE',
        telefone: '(81) 4009-1234',
        email: 'suporte@tecparts.com.br',
      },
      {
        tipoPessoa: 'Física',
        nome: 'Ana Paula Mendes',
        cpf: '123.456.789-00',
        dataNascimento: new Date('1987-08-15'),
        telefone: '(11) 99999-1111',
        email: 'ana.mendes@email.com',
        cep: '01111-000',
        logradouro: 'Rua Bela Vista',
        bairro: 'Jardins',
        localidade: 'São Paulo',
        uf: 'SP',
      },
      {
        tipoPessoa: 'Física',
        nome: 'Carlos Henrique Souza',
        cpf: '234.567.890-11',
        dataNascimento: new Date('1990-03-22'),
        telefone: '(21) 98888-2222',
        email: 'carloshs@email.com',
        cep: '22000-000',
        logradouro: 'Av. Atlântica',
        bairro: 'Copacabana',
        localidade: 'Rio de Janeiro',
        uf: 'RJ',
      },
      {
        tipoPessoa: 'Física',
        nome: 'Fernanda Oliveira',
        cpf: '345.678.901-22',
        dataNascimento: new Date('1985-12-05'),
        telefone: '(31) 97777-3333',
        email: 'fernanda.oliveira@email.com',
        cep: '30100-000',
        logradouro: 'Rua das Flores',
        bairro: 'Savassi',
        localidade: 'Belo Horizonte',
        uf: 'MG',
      },
      {
        tipoPessoa: 'Física',
        nome: 'Rafael Lima',
        cpf: '456.789.012-33',
        dataNascimento: new Date('1995-07-10'),
        telefone: '(41) 96666-4444',
        email: 'rafael.lima@email.com',
        cep: '80000-000',
        logradouro: 'Av. República',
        bairro: 'Centro Cívico',
        localidade: 'Curitiba',
        uf: 'PR',
      },
      {
        tipoPessoa: 'Física',
        nome: 'Juliana Costa',
        cpf: '567.890.123-44',
        dataNascimento: new Date('1992-01-25'),
        telefone: '(81) 95555-5555',
        email: 'juliana.costa@email.com',
        cep: '50000-000',
        logradouro: 'Rua da Aurora',
        bairro: 'Boa Vista',
        localidade: 'Recife',
        uf: 'PE',
      },
    ],
  })
  console.log('Fornecedores inseridos com sucesso.')
}